Update gitlab-release.yml

diff --git a/.github/workflows/gitlab-release.yml b/.github/workflows/gitlab-release.yml
--- a/.github/workflows/gitlab-release.yml
+++ b/.github/workflows/gitlab-release.yml
@@ -105,6 +105,10 @@ jobs:
           fi
           
           export ISISROOT=$CONDA_PREFIX
+          echo $ISISROOT
+          echo "Checking spiceinit location: $ISISROOT/bin/spiceinit"
+          ls $ISISROOT/bin/spiceinit || echo "spiceinit not found"
+
           spiceinit -H
       
       - name: Cleanup Anaconda package if spiceinit fails
